spring:
  profiles:
    active:
      - dev
---
spring: 
  profiles: dev
    application: 
       name: microservicecloud-config-paul-dev 
       
---
spring: 
  profiles: test
    application: 
       name: microservicecloud-config-paul-test